export const BacklogEntryDummyData = [
  {
    id: 1,
    title: "The First Berserker Khazan",
    playtime: 66,
    imageLink:
      "https://howlongtobeat.com/games/141849_The_First_Berserker_Khazan.jpg",
    imageAlt: "How to Beat Berserker Khazan",
    genre: ["Action", "Adventure", "Role-Playing"],
    platform: ["PC"],
    status: "In Progress",
    owned: true,
    interest: 10,
    reviewStars: 4,
    review: "Das Game ist einfach Liebe man und satisfing!",
    note: "Replay mit NG+ auf hoeherer Schwierigkeit!",
    mainTime: 35,
    mainPlusExtraTime: 50,
    completionTime: 57,
  },
  {
    id: 2,
    title: "Batman: Arkham Knight",
    playtime: 40,
    imageLink:
      "https://howlongtobeat.com/games/Batman_Arkham_Knight_Cover_Art.jpg",
    imageAlt: "How to Beat Batman",
    genre: [
      "Third-Person",
      "Action",
      "Adventure",
      "Beat em Up",
      "Open World",
      "Puzzle",
      "Vehicular Combat",
    ],
    platform: ["PC"],
    status: "Completed",
    owned: true,
    interest: 8,
    reviewStars: 5,
    review: "I am the shadow, for Gotham!",
    note: "Endlich mal beenden haha",
    mainTime: 17,
    mainPlusExtraTime: 31,
    completionTime: 51,
  },
  {
    id: 3,
    title: "SnowRunner",
    playtime: 79,
    imageLink: "https://howlongtobeat.com/games/77675_SnowRunner.jpg",
    imageAlt: "How to Beat SnowRunner",
    genre: ["Racing/Driving", "Simulation"],
    platform: ["PC"],
    status: "In Progress",
    owned: true,
    interest: 7,
    reviewStars: 5,
    review: "So chiliig Gespräche mit den Jungs geht fast nirgendwo anders!",
    note: "Ich werd safe 1500 Stunden brauchen für alle Maps!",
    mainTime: 89,
    mainPlusExtraTime: 159,
    completionTime: 239,
  },
  {
    id: 4,
    title: "Super Mario Galaxy 2",
    playtime: 2,
    imageLink:
      "https://howlongtobeat.com/games/Super_Mario_Galaxy_2_Box_Art.jpg",
    imageAlt: "How to Beat Super Mario Galaxy",
    genre: ["", ""],
    platform: ["Nintendo Switch"],
    status: "In Progress",
    owned: true,
    interest: 10,
    reviewStars: 4,
    review: "Extrem chilliges Spiel, das ich schon mal gespielt habe!",
    note: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    mainTime: 13,
    mainPlusExtraTime: 21,
    completionTime: 33,
  },
  {
    id: 5,
    title: "Marvel's Spider-Man 2",
    playtime: 33,
    imageLink: "https://howlongtobeat.com/games/79769_Marvels_Spider-Man_2.png",
    imageAlt: "How to Beat Marvel's Spider-Man 2",
    genre: ["Action", "Adventure", "Superhero"],
    platform: ["Playstation 5"],
    status: "Completed",
    owned: true,
    interest: 10,
    reviewStars: 4,
    review: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    note: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    mainTime: 17,
    mainPlusExtraTime: 24,
    completionTime: 29,
  },
  {
    id: 6,
    title: "Borderlands 4",
    playtime: 55,
    imageLink: "https://howlongtobeat.com/games/91605_Borderlands_4.jpg",
    imageAlt: "How to Beat Borderlands 4",
    genre: ["First-Person", "Shooter"],
    platform: ["PC"],
    status: "In Progress",
    owned: true,
    interest: 10,
    reviewStars: 5,
    review: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    note: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    mainTime: 28,
    mainPlusExtraTime: 47,
    completionTime: 91,
  },
  {
    id: 7,
    title: "Sea of Thieves",
    playtime: 30,
    imageLink: "https://howlongtobeat.com/games/38053_Sea_of_Thieves.jpg",
    imageAlt: "How to Beat Sea of Thieves",
    genre: ["Action", "Adventure", "Open World"],
    platform: ["Xbox Series X/S"],
    status: "Completed",
    owned: true,
    interest: 10,
    reviewStars: 3,
    review: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    note: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    mainTime: 72,
    mainPlusExtraTime: 226,
    completionTime: 0,
  },
  {
    id: 8,
    title: "Dispatch",
    playtime: 0,
    imageLink: "https://howlongtobeat.com/games/160618_Dispatch.jpg",
    imageAlt: "How to Beat Dispatch",
    genre: ["Action", "Adventure", "Management"],
    platform: ["PC"],
    status: "Not Played",
    owned: false,
    interest: 6,
    reviewStars: 1,
    review: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    note: "Das Spiel ist sehr schwer, aber ich habe es schon mal gespielt!",
    mainTime: 9,
    mainPlusExtraTime: 10,
    completionTime: 17,
  },
  {
    id: 9,
    title: "Donkey Kong Country Mania",
    playtime: 0,
    imageLink:
      "https://howlongtobeat.com/games/162338_Donkey_Kong_Country_Mania.jpg",
    imageAlt: "How to Beat Donkey Kong Country Mania",
    genre: ["Scrolling", "Platform"],
    platform: ["Super Nintendo"],
    status: "Not Played",
    owned: false,
    interest: 3,
    mainTime: 3.5,
    mainPlusExtraTime: 0,
    completionTime: 0,
  },
];
