export const BacklogEntryDummyData = [
  {
    id: 1,
    title: "The First Berserker Khazan",
    imageLink:
      "https://howlongtobeat.com/games/141849_The_First_Berserker_Khazan.jpg",
    imageAlt: "How to Beat Berserker Khazan",
    genre: ["Action", "Adventure", "Role-Playing"],
    platform: ["PC"],
    status: "In Progress",
    owned: true,
    interest: 10,
    reviewStars: 4,
    review: "Das Game ist einfach Liebe man und satisfing!",
    note: "Replay mit NG+ auf hoeherer Schwierigkeit!",
    howLongToBeat: [35, 50, 57],
  },
  {
    id: 2,
    title: "Batman: Arkham Knight",
    imageLink:
      "https://howlongtobeat.com/games/Batman_Arkham_Knight_Cover_Art.jpg",
    imageAlt: "How to Beat Batman",
    genre: [
      "Third-Person",
      "Action",
      "Adventure",
      "Beat em Up",
      "Open World",
      "Puzzle",
      "Vehicular Combat",
    ],
    platform: ["PC"],
    status: "In Progress",
    owned: true,
    interest: 8,
    reviewStars: 5,
    review: "I am the shadow, for Gotham!",
    note: "Endlich mal beenden haha",
    howLongToBeat: [17, 31, 51],
  },
  {
    id: 3,
    title: "SnowRunner",
    imageLink: "https://howlongtobeat.com/games/77675_SnowRunner.jpg",
    imageAlt: "How to Beat SnowRunner",
    genre: ["Racing/Driving", "Simulation"],
    platform: ["PC"],
    status: "In Progress",
    owned: true,
    interest: 7,
    reviewStars: 5,
    review: "So chiliig Gespräche mit den Jungs geht fast nirgendwo anders!",
    note: "Ich werd safe 1500 Stunden brauchen für alle Maps!",
    howLongToBeat: [89, 159, 239],
  },
];